+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Sat Aug 26 16:59:14 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL 'aide gcc'
+ pkgs='aide gcc'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'aide gcc' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmph4gj_qpd
+ '[' -z '' ']'
+ tmpfile=/tmp/tmph4gj_qpd
+ sed -i '$a/home DATAONLY' /etc/aide.conf
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Sat Aug 26 16:59:33 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Aug 26 16:59:33 2023 - INFO  - Start to run test.
+ aide --init
Start timestamp: 2023-08-26 16:59:33 +0000 (AIDE 0.18.5)
AIDE successfully initialized database.
New AIDE database written to /var/lib/aide/aide.db.new.gz

Number of entries:	53050

---------------------------------------------------
The attributes of the (uncompressed) database(s):
---------------------------------------------------

/var/lib/aide/aide.db.new.gz
 MD5       : cZT73QmdPdBiv2Zf37Gf+w==
 SHA1      : T34k5BBzkBlhqZ1ctQUFwvfhzcw=
 SHA256    : ePP9lVo/N09+ZG8w6Uxfgy75jV7ngHKX
             H/xcVfVPf34=
 SHA512    : j9pYn6M1PL65Pr9MmIr4vztygBumTclL
             BQ907pZ2EPDTZDR0BZiKv4Qp+b+2xRRL
             C0wt1HdOLyYRogyZwzMaBQ==
 RMD160    : i15jVtVnLPLm0zxu2sIKjlAmzak=
 TIGER     : Bpjca4pkRqwLSQKuaUp7Q6YIMamNjYgV
 CRC32     : jeaZJg==
 WHIRLPOOL : xK+hwIvFCPrJB/enrARC2j4PlhBTF2sm
             dRxyDHkfuz6Py9YXTeQpGK3ZXWFF9DUb
             Lxnml+PsTQ/HtteKM6sS6A==
 GOST      : vBIXNzJhSHJ0GIckG6YyUiVCb5Z1FBln
             QA+fvCm+ip0=
 STRIBOG256: 9s97wqWTafC2r36wT/bnD1zO6dC/arHQ
             oEGpjdqlP3o=
 STRIBOG512: ZO9e0yR/5hwoB+E6HjTG83yRGokBvAVh
             pxfsxU01lEP/ziJi5dr/ABUDPhLp6Ti9
             HW3gRKRhqnvEmIMVaJwMrg==
 SM3       : X/rpSdxvWuTEq7Ad5JegzQzc7ox4Ihlw
             T6SFeSb9Iq0=


End timestamp: 2023-08-26 16:59:45 +0000 (run time: 0m 12s)
+ CHECK_RESULT 0 0 0 'initialization failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='initialization failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
+ useradd testuser
+ aide -c /etc/aide.conf --update
+ grep -A 10 'Changed entries:'
+ grep /etc/group
f > ... mci.H..  : /etc/group
f < ... .c..H..  : /etc/group-
+ CHECK_RESULT 0 0 0 'Update execution failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Update execution failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ test -f /var/lib/aide/aide.db.new.gz
+ CHECK_RESULT 0 0 0 'Update execution failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Update execution failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
+ aide --check
+ grep Changed entries:
grep: entries:: No such file or directory
+ CHECK_RESULT 2 0 1 'Check execution failed'
+ actual_result=2
+ expect_result=0
+ mode=1
+ error_log='Check execution failed'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 1 -eq 0 ']'
+ test 2x == 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Aug 26 17:00:43 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Sat Aug 26 17:00:43 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Sat Aug 26 17:00:43 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmph4gj_qpd ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmph4gj_qpd
+ '[' 0 -ne 0 ']'
+ userdel -rf testuser
+ rm -rf testlog /var/log/aide/aide.log /var/lib/aide/aide.db.gz
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Sat Aug 26 17:00:44 2023 - INFO  - End to restore the test environment.
