+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Thu Aug 31 14:33:13 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL 'valgrind glibc-devel glibc-debuginfo'
+ pkgs='valgrind glibc-devel glibc-debuginfo'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs 'valgrind glibc-devel glibc-debuginfo' --node 1 --tempfile ''
Thu Aug 31 14:33:21 2023 - ERROR - pkgs:(valgrind glibc-debuginfo) not found
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu Aug 31 14:33:21 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu Aug 31 14:33:22 2023 - INFO  - Start to run test.
+ valgrind --version
+ grep -E 'valgrind-[0-9]+.[0-9]+.[0-9]+'
oe_test_valgrind.sh: line 29: valgrind: command not found
+ CHECK_RESULT 1 0 0 'check valgrind version error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='check valgrind version error'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'check valgrind version error'
+ LOG_ERROR 'check valgrind version error'
+ message='check valgrind version error'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'check valgrind version error'
Thu Aug 31 14:33:22 2023 - ERROR - check valgrind version error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_valgrind.sh line 30'
+ message='oe_test_valgrind.sh line 30'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_valgrind.sh line 30'
Thu Aug 31 14:33:23 2023 - ERROR - oe_test_valgrind.sh line 30
+ return 0
+ cat
+ gcc -g -o valgrind_test valgrind_test.c
+ CHECK_RESULT 0 0 0 'compile valgrind_test error'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='compile valgrind_test error'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ valgrind --tool=memcheck --leak-check=full ./valgrind_test
+ CHECK_RESULT 127 0 0 'execute valgrind command error'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='execute valgrind command error'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'execute valgrind command error'
+ LOG_ERROR 'execute valgrind command error'
+ message='execute valgrind command error'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'execute valgrind command error'
Thu Aug 31 14:33:25 2023 - ERROR - execute valgrind command error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_valgrind.sh line 44'
+ message='oe_test_valgrind.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_valgrind.sh line 44'
Thu Aug 31 14:33:25 2023 - ERROR - oe_test_valgrind.sh line 44
+ return 0
+ grep '8 bytes in 1 blocks are definitely lost in loss record' valgrind_test.log
+ CHECK_RESULT 1 0 0 'check valgrind_test.log error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='check valgrind_test.log error'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'check valgrind_test.log error'
+ LOG_ERROR 'check valgrind_test.log error'
+ message='check valgrind_test.log error'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'check valgrind_test.log error'
Thu Aug 31 14:33:25 2023 - ERROR - check valgrind_test.log error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_valgrind.sh line 46'
+ message='oe_test_valgrind.sh line 46'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_valgrind.sh line 46'
Thu Aug 31 14:33:26 2023 - ERROR - oe_test_valgrind.sh line 46
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Thu Aug 31 14:33:26 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Aug 31 14:33:27 2023 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu Aug 31 14:33:27 2023 - INFO  - start environment cleanup.
+ rm -rf valgrind_test valgrind_test.c valgrind_test.log
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Thu Aug 31 14:33:27 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Thu Aug 31 14:33:28 2023 - INFO  - Finish environment cleanup!
