+ source ./common/disk_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ grep expect
+ rpm -qa
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment!'
+ message='Start to prepare the test environment!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment!'
Tue Aug 29 15:38:35 2023 - INFO  - Start to prepare the test environment!
+ DNF_INSTALL lvm2
+ pkgs=lvm2
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs lvm2 --node 1 --tempfile ''
Tue Aug 29 15:38:35 2023 - INFO  - pkgs:(lvm2) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen-riscv/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=sr0
+ disk_list=($disks)
+ local_disk=sr0
+ local_disk1=
+ local_disk2=
+ local_disk3=
++ cat /etc/os-release
++ awk -F = '{print$NF}'
++ grep VERSION_ID
++ awk -F '"' '{print$2}'
+ version_id=23.09
+ LOG_INFO 'End to prepare the test environment!'
+ message='End to prepare the test environment!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment!'
Tue Aug 29 15:38:36 2023 - INFO  - End to prepare the test environment!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Tue Aug 29 15:38:36 2023 - INFO  - Start executing testcase!
+ pvcreate -y /dev/sr0
  Device open 11:0 has no path names.
  Cannot use /dev/sr0: device not found
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvremove_001.sh line 31'
+ message='oe_test_lvm2_pvremove_001.sh line 31'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvremove_001.sh line 31'
Tue Aug 29 15:38:36 2023 - ERROR - oe_test_lvm2_pvremove_001.sh line 31
+ return 0
+ pvremove -f /dev/sr0
  Device open 11:0 has no path names.
  Cannot use /dev/sr0: device not found
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvremove_001.sh line 33'
+ message='oe_test_lvm2_pvremove_001.sh line 33'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvremove_001.sh line 33'
Tue Aug 29 15:38:36 2023 - ERROR - oe_test_lvm2_pvremove_001.sh line 33
+ return 0
+ pvcreate -y /dev/sr0
  Device open 11:0 has no path names.
  Cannot use /dev/sr0: device not found
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvremove_001.sh line 35'
+ message='oe_test_lvm2_pvremove_001.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvremove_001.sh line 35'
Tue Aug 29 15:38:37 2023 - ERROR - oe_test_lvm2_pvremove_001.sh line 35
+ return 0
+ pvremove -f /dev/sr0 --reportformat basic
+ grep 'successfully wiped'
  Device open 11:0 has no path names.
  Cannot use /dev/sr0: device not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvremove_001.sh line 37'
+ message='oe_test_lvm2_pvremove_001.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvremove_001.sh line 37'
Tue Aug 29 15:38:37 2023 - ERROR - oe_test_lvm2_pvremove_001.sh line 37
+ return 0
+ pvcreate -y /dev/sr0
  Device open 11:0 has no path names.
  Cannot use /dev/sr0: device not found
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvremove_001.sh line 39'
+ message='oe_test_lvm2_pvremove_001.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvremove_001.sh line 39'
Tue Aug 29 15:38:37 2023 - ERROR - oe_test_lvm2_pvremove_001.sh line 39
+ return 0
+ pvremove -f /dev/sr0 --reportformat json
+ grep 'successfully wiped'
  Device open 11:0 has no path names.
  Cannot use /dev/sr0: device not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvremove_001.sh line 41'
+ message='oe_test_lvm2_pvremove_001.sh line 41'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvremove_001.sh line 41'
Tue Aug 29 15:38:38 2023 - ERROR - oe_test_lvm2_pvremove_001.sh line 41
+ return 0
+ pvcreate -y /dev/sr0
  Device open 11:0 has no path names.
  Cannot use /dev/sr0: device not found
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvremove_001.sh line 43'
+ message='oe_test_lvm2_pvremove_001.sh line 43'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvremove_001.sh line 43'
Tue Aug 29 15:38:38 2023 - ERROR - oe_test_lvm2_pvremove_001.sh line 43
+ return 0
+ grep 'successfully wiped'
+ pvremove -f /dev/sr0 -d
  Device open 11:0 has no path names.
  Cannot use /dev/sr0: device not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvremove_001.sh line 45'
+ message='oe_test_lvm2_pvremove_001.sh line 45'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvremove_001.sh line 45'
Tue Aug 29 15:38:39 2023 - ERROR - oe_test_lvm2_pvremove_001.sh line 45
+ return 0
+ pvcreate -y /dev/sr0
  Device open 11:0 has no path names.
  Cannot use /dev/sr0: device not found
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvremove_001.sh line 47'
+ message='oe_test_lvm2_pvremove_001.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvremove_001.sh line 47'
Tue Aug 29 15:38:39 2023 - ERROR - oe_test_lvm2_pvremove_001.sh line 47
+ return 0
+ pvremove -f /dev/sr0 --driverloaded y
+ grep 'successfully wiped'
  Device open 11:0 has no path names.
  Cannot use /dev/sr0: device not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvremove_001.sh line 49'
+ message='oe_test_lvm2_pvremove_001.sh line 49'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvremove_001.sh line 49'
Tue Aug 29 15:38:39 2023 - ERROR - oe_test_lvm2_pvremove_001.sh line 49
+ return 0
+ pvcreate -y /dev/sr0
  Device open 11:0 has no path names.
  Cannot use /dev/sr0: device not found
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvremove_001.sh line 51'
+ message='oe_test_lvm2_pvremove_001.sh line 51'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvremove_001.sh line 51'
Tue Aug 29 15:38:40 2023 - ERROR - oe_test_lvm2_pvremove_001.sh line 51
+ return 0
+ pvremove --version
+ grep LVM
  LVM version:     2.03.21(2) (2023-04-21)
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pvcreate -y /dev/sr0
  Device open 11:0 has no path names.
  Cannot use /dev/sr0: device not found
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvremove_001.sh line 55'
+ message='oe_test_lvm2_pvremove_001.sh line 55'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvremove_001.sh line 55'
Tue Aug 29 15:38:40 2023 - ERROR - oe_test_lvm2_pvremove_001.sh line 55
+ return 0
+ '[23.09' = '22.03]'
oe_test_lvm2_pvremove_001.sh: line 56: [23.09: command not found
+ pvcreate -y /dev/sr0
  Device open 11:0 has no path names.
  Cannot use /dev/sr0: device not found
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvremove_001.sh line 69'
+ message='oe_test_lvm2_pvremove_001.sh line 69'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvremove_001.sh line 69'
Tue Aug 29 15:38:40 2023 - ERROR - oe_test_lvm2_pvremove_001.sh line 69
+ return 0
+ pvremove --longhelp
+ grep PV
  pvremove PV ...
	[    --devices PV ]
        e.g. PV, VG, LV, Size, Number, String, Tag.
        PV
        For commands managing physical extents, a PV positional arg
        PV[:PE-PE]... is start and end range (inclusive),
        PV[:PE+PE]... is start and length range (counting from 0).
        tags in place of a VG, LV or PV.
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End executing testcase!'
+ message='End executing testcase!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End executing testcase!'
Tue Aug 29 15:38:40 2023 - INFO  - End executing testcase!
+ CASE_RESULT 0
+ case_re=0
+ test -z 13
+ test 13 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Aug 29 15:38:40 2023 - ERROR - failed to execute the case.
+ exit 13
+ post_test
+ LOG_INFO 'Start environment cleanup.'
+ message='Start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environment cleanup.'
Tue Aug 29 15:38:40 2023 - INFO  - Start environment cleanup.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Tue Aug 29 15:38:40 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Tue Aug 29 15:38:40 2023 - INFO  - Finish environment cleanup.
