+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ grep expect
+ rpm -qa
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Sat Sep  2 01:01:35 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL 'strongswan podman tar'
+ pkgs='strongswan podman tar'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'strongswan podman tar' --node 1 --tempfile ''
+ tmpfile2='Last metadata expiration check: 0:11:22 ago on Sat 02 Sep 2023 12:50:59 AM CST.
Package tar-2:1.35-1.oe2309.riscv64 is already installed.
Error: 
 Problem: conflicting requests
  - nothing provides containers-common needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline
  - nothing provides catatonit needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline
  - nothing provides crun needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ '[' -z '' ']'
+ tmpfile='Last metadata expiration check: 0:11:22 ago on Sat 02 Sep 2023 12:50:59 AM CST.
Package tar-2:1.35-1.oe2309.riscv64 is already installed.
Error: 
 Problem: conflicting requests
  - nothing provides containers-common needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline
  - nothing provides catatonit needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline
  - nothing provides crun needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ tar -xvf ./common/data.tar.gz
+ podman stop -all
oe_test_service_charon-cmd_01.sh: line 26: podman: command not found
++ podman ps -qa
oe_test_service_charon-cmd_01.sh: line 27: podman: command not found
+ podman rm -f
oe_test_service_charon-cmd_01.sh: line 27: podman: command not found
+ podman load
oe_test_service_charon-cmd_01.sh: line 28: podman: command not found
+ podman run -itd --name vpn --env-file ./test_file/vpn.env -p 700:700/udp -p 4700:4700/udp -d --privileged docker.io/hwdsl2/ipsec-vpn-server:latest
oe_test_service_charon-cmd_01.sh: line 29: podman: command not found
+ SLEEP_WAIT 5 'strongswan stop'
+ wait_time=5
+ cmd='strongswan stop'
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd 'strongswan stop' --mode 1
/bin/sh: line 1: strongswan: command not found
+ SLEEP_WAIT 3 'rm -rf strongswan_test*.log'
+ wait_time=3
+ cmd='rm -rf strongswan_test*.log'
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd 'rm -rf strongswan_test*.log' --mode 1
++ date '+%Y-%m-%d %T'
+ log_time='2023-09-02 01:02:28'
+ grep shared /etc/strongswan/ipsec.conf
grep: /etc/strongswan/ipsec.conf: No such file or directory
+ cat ./test_file/ipsec_add.conf
oe_test_service_charon-cmd_01.sh: line 33: /etc/strongswan/ipsec.conf: No such file or directory
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Sat Sep  2 01:02:30 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Sep  2 01:02:31 2023 - INFO  - Start to run test.
+ strongswan start
oe_test_service_charon-cmd_01.sh: line 39: strongswan: command not found
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ charon-cmd --help
oe_test_service_charon-cmd_01.sh: line 41: charon-cmd: command not found
+ grep 'Usage: charon-cmd'
+ CHECK_RESULT 1 0 0 'Failed to check the --help'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to check the --help'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to check the --help'
+ LOG_ERROR 'Failed to check the --help'
+ message='Failed to check the --help'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to check the --help'
Sat Sep  2 01:02:37 2023 - ERROR - Failed to check the --help
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_charon-cmd_01.sh line 42'
+ message='oe_test_service_charon-cmd_01.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_charon-cmd_01.sh line 42'
Sat Sep  2 01:02:38 2023 - ERROR - oe_test_service_charon-cmd_01.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ charon-cmd --version
oe_test_service_charon-cmd_01.sh: line 43: charon-cmd: command not found
+ grep 'charon-cmd, strongSwan'
+ CHECK_RESULT 1 0 0 'Failed to check the --version'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to check the --version'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to check the --version'
+ LOG_ERROR 'Failed to check the --version'
+ message='Failed to check the --version'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to check the --version'
Sat Sep  2 01:02:39 2023 - ERROR - Failed to check the --version
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_charon-cmd_01.sh line 44'
+ message='oe_test_service_charon-cmd_01.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_charon-cmd_01.sh line 44'
Sat Sep  2 01:02:40 2023 - ERROR - oe_test_service_charon-cmd_01.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ pgrep -f 'charon-cmd --host'
+ charon-cmd --host 114.114.114.114 --identity shared
+ CHECK_RESULT 1 0 0 'Failed to check the --host and --identity'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to check the --host and --identity'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to check the --host and --identity'
+ LOG_ERROR 'Failed to check the --host and --identity'
+ message='Failed to check the --host and --identity'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to check the --host and --identity'
Sat Sep  2 01:02:41 2023 - ERROR - Failed to check the --host and --identity
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_charon-cmd_01.sh line 47'
+ message='oe_test_service_charon-cmd_01.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_charon-cmd_01.sh line 47'
Sat Sep  2 01:02:42 2023 - ERROR - oe_test_service_charon-cmd_01.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ pgrep -f 'charon-cmd --host 114.114.114.114 --identity shared --eap-identity'
+ charon-cmd --host 114.114.114.114 --identity shared --eap-identity shared
+ CHECK_RESULT 1 0 0 'Failed to check the --eap-identity'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to check the --eap-identity'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to check the --eap-identity'
+ LOG_ERROR 'Failed to check the --eap-identity'
+ message='Failed to check the --eap-identity'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to check the --eap-identity'
Sat Sep  2 01:02:44 2023 - ERROR - Failed to check the --eap-identity
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_charon-cmd_01.sh line 50'
+ message='oe_test_service_charon-cmd_01.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_charon-cmd_01.sh line 50'
Sat Sep  2 01:02:45 2023 - ERROR - oe_test_service_charon-cmd_01.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
++ pgrep -f 'charon-cmd --host 114.114.114.114 --identity shared --eap-identity'
+ kill -9
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
+ pgrep -f '\-\-xauth-username test_sun'
+ charon-cmd --host 114.114.114.114 --identity shared --xauth-username test_sun
+ CHECK_RESULT 1 1 0 0 'Failed to check the --xauth-username'
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log=0
+ exit_mode='Failed to check the --xauth-username'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
++ pgrep -f 'xauth-username test_sun'
+ kill -9
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
+ pgrep -f '\-\-remote-identity'
+ charon-cmd --host 114.114.114.114 --identity shared --remote-identity shared
+ CHECK_RESULT 1 0 0 'Failed to check the --xauth-username'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to check the --xauth-username'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to check the --xauth-username'
+ LOG_ERROR 'Failed to check the --xauth-username'
+ message='Failed to check the --xauth-username'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to check the --xauth-username'
Sat Sep  2 01:02:48 2023 - ERROR - Failed to check the --xauth-username
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_charon-cmd_01.sh line 58'
+ message='oe_test_service_charon-cmd_01.sh line 58'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_charon-cmd_01.sh line 58'
Sat Sep  2 01:02:49 2023 - ERROR - oe_test_service_charon-cmd_01.sh line 58
+ '[' 0 -eq 1 ']'
+ return 0
++ pgrep -f remote-identity
+ kill -9
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
+ pgrep -f 'test_file\/test_strongswan.pem'
+ charon-cmd --host 114.114.114.114 --identity shared --cert ./test_file/test_strongswan.pem
+ CHECK_RESULT 1 0 0 'Failed to check the --cert'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to check the --cert'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to check the --cert'
+ LOG_ERROR 'Failed to check the --cert'
+ message='Failed to check the --cert'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to check the --cert'
Sat Sep  2 01:02:52 2023 - ERROR - Failed to check the --cert
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_charon-cmd_01.sh line 62'
+ message='oe_test_service_charon-cmd_01.sh line 62'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_charon-cmd_01.sh line 62'
Sat Sep  2 01:02:53 2023 - ERROR - oe_test_service_charon-cmd_01.sh line 62
+ '[' 0 -eq 1 ']'
+ return 0
++ pgrep -f 'test_file\/test_strongswan.pem'
+ kill -9
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Sep  2 01:02:54 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 6
+ test 6 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sat Sep  2 01:02:55 2023 - ERROR - failed to execute the case.
+ exit 6
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Sat Sep  2 01:02:57 2023 - INFO  - Start to restore the test environment.
+ pgrep -f strongswan
2093
2094
2096
+ strongswan stop
oe_test_service_charon-cmd_01.sh: line 69: strongswan: command not found
+ SLEEP_WAIT 3 'podman stop -all'
+ wait_time=3
+ cmd='podman stop -all'
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd 'podman stop -all' --mode 1
/bin/sh: line 1: podman: command not found
++ podman ps -qa
oe_test_service_charon-cmd_01.sh: line 71: podman: command not found
+ podman rm -f
oe_test_service_charon-cmd_01.sh: line 71: podman: command not found
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Last metadata expiration check: 0:11:22 ago on Sat 02 Sep 2023 12:50:59 AM CST.
Package tar-2:1.35-1.oe2309.riscv64 is already installed.
Error: 
 Problem: conflicting requests
  - nothing provides containers-common needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline
  - nothing provides catatonit needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline
  - nothing provides crun needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages) ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Last metadata expiration check: 0:11:22 ago on Sat 02 Sep 2023 12:50:59 AM CST.
Package tar-2:1.35-1.oe2309.riscv64 is already installed.
Error: 
 Problem: conflicting requests
  - nothing provides containers-common needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline
  - nothing provides catatonit needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline
  - nothing provides crun needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
Traceback (most recent call last):
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 192, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 163, in rpm_remove
    with open(tmpfile, "r") as f:
         ^^^^^^^^^^^^^^^^^^
OSError: [Errno 36] File name too long: "Last metadata expiration check: 0:11:22 ago on Sat 02 Sep 2023 12:50:59 AM CST.\nPackage tar-2:1.35-1.oe2309.riscv64 is already installed.\nError: \n Problem: conflicting requests\n  - nothing provides containers-common needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline\n  - nothing provides catatonit needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline\n  - nothing provides crun needed by podman-1:4.5.1-1.oe2309.riscv64 from mainline\n(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)"
+ '[' 0 -ne 0 ']'
+ rm -rf strongswan_test_charon-cmd-cert.log strongswan_test_charon-cmd-host-eapidentity.log strongswan_test_charon-cmd-host-identity.log strongswan_test_charon-cmd-remote-identity.log test_file
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Sat Sep  2 01:03:04 2023 - INFO  - End to restore the test environment.
