+ source ../common_lib/fsio_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf /tmp/point120230901153517 /tmp/point220230901153517 /tmp/point320230901153517
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Fri Sep  1 15:35:35 2023 - INFO  - Start to prepare the database config.
+ cur_lang=en_US.UTF-8
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ point_list=($(CREATE_FS ext3))
++ CREATE_FS ext3
++ fs_type=ext3
+++ date +%Y%m%d%H%M%S
++ cur_date=20230901153535
+++ CREATE_VG
++++ date +%Y%m%d%H%M%S
+++ cur_date=20230901153535
++++ lsblk
++++ grep disk
++++ awk '{print $1}'
++++ tail -n 1
+++ free_disk=vda
+++ disk_name=/dev/vda
+++ pvcreate /dev/vda -f
+++ [[ 5 -eq 0 ]]
++++ pvcreate /dev/vda
++++ grep test_vggroup
++++ cut -d '"' -f 4
+++ vggroup=
+++ printf
printf: usage: printf [-v var] format [arguments]
++ vggroup=
++ count=1
++ msg=' '
++ for fs in ${fs_type[@]}
++ lvname=test_lv120230901153535
++ point=/tmp/point120230901153535
++ lvcreate -n test_lv120230901153535 -L 512M -y
  No command with matching syntax recognised.  Run 'lvcreate --help' for more information.
  Nearest similar command has syntax:
++ mkfs -t ext3 /dev//test_lv120230901153535
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv120230901153535 does not exist and no size was specified.
++ mkdir /tmp/point120230901153535
++ mount /dev//test_lv120230901153535 /tmp/point120230901153535
mount: /tmp/point120230901153535: special device /dev//test_lv120230901153535 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230901153535 '
++ count=2
++ echo /tmp/point120230901153535
+ ext3_point=
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Fri Sep  1 15:35:36 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Sep  1 15:35:36 2023 - INFO  - Start to run test.
+ mv /mnt/testmv
+ grep 'Device or resource busy'
+ CHECK_RESULT 1 0 0 'Move mounted point unexpectly.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Move mounted point unexpectly.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Move mounted point unexpectly.'
+ LOG_ERROR 'Move mounted point unexpectly.'
+ message='Move mounted point unexpectly.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Move mounted point unexpectly.'
Fri Sep  1 15:35:37 2023 - ERROR - Move mounted point unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mv_rm_mount.sh line 33'
+ message='oe_test_FSIO_mv_rm_mount.sh line 33'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mv_rm_mount.sh line 33'
Fri Sep  1 15:35:37 2023 - ERROR - oe_test_FSIO_mv_rm_mount.sh line 33
+ return 0
+ rm -rf
+ grep 'Device or resource busy'
+ CHECK_RESULT 1 0 0 'Remove mounted point unexpectly.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Remove mounted point unexpectly.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Remove mounted point unexpectly.'
+ LOG_ERROR 'Remove mounted point unexpectly.'
+ message='Remove mounted point unexpectly.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Remove mounted point unexpectly.'
Fri Sep  1 15:35:37 2023 - ERROR - Remove mounted point unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mv_rm_mount.sh line 35'
+ message='oe_test_FSIO_mv_rm_mount.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mv_rm_mount.sh line 35'
Fri Sep  1 15:35:38 2023 - ERROR - oe_test_FSIO_mv_rm_mount.sh line 35
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Sep  1 15:35:38 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Sep  1 15:35:39 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Sep  1 15:35:39 2023 - INFO  - Start to restore the test environment.
++ echo /tmp/point120230901153535
+ list=/tmp/point120230901153535
+ REMOVE_FS /tmp/point120230901153535
+ point_list=($1)
++ seq 0 0
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point120230901153535
++ df -T
++ grep /tmp/point120230901153535
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ rm -rf /mnt/testmv
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Sep  1 15:35:40 2023 - INFO  - End to restore the test environment.
