+ source ../common/common_ndisc6.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Fri Sep  1 20:37:43 2023 - INFO  - Start to prepare the test environment.
+ deploy_env
+ DNF_INSTALL 'ndisc6 xinetd time'
+ pkgs='ndisc6 xinetd time'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs 'ndisc6 xinetd time' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpvq_3t61e
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpvq_3t61e
++ hostname
+ hostname_init=openeuler-riscv64
+ hostname newlocalhost
++ ip addr show
++ grep -w inet6
++ awk '{print $2}'
++ awk -F / '{print $1}'
++ awk 'NR==1{print $1}'
+ NODE1_IPV6=::1
++ P_SSH_CMD --node 2 --cmd 'ip addr show '
++ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py --node 2 --cmd 'ip addr show '
++ grep -w inet6
++ awk '{print $2}'
++ awk -F / '{print $1}'
++ awk 'NR==1{print $1}'
Fri Sep  1 20:38:06 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ NODE2_IPV6=
+ cp /etc/resolv.conf /etc/resolv.conf-bak
+ sed -i 's/name/#&/' /etc/resolv.conf
+ sed -i 6s/yes/no/g /etc/xinetd.d/echo-stream
+ systemctl restart xinetd
+ DNF_INSTALL xinetd 2
+ pkgs=xinetd
+ node=2
+ '[' -z /tmp/tmpvq_3t61e ']'
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs xinetd --node 2 --tempfile /tmp/tmpvq_3t61e
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 176, in <module>
    exitcode, output = rpm_install(args.pkgs, args.node, args.tempfile)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 66, in rpm_install
    conn = ssh_cmd.pssh_conn(
           ^^^^^^^^^^^^^^^^^^
  File "/root/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
+ tmpfile2=
+ '[' -z /tmp/tmpvq_3t61e ']'
+ P_SSH_CMD --node 2 --cmd 'sed -i '\''6s/yes/no/g'\'' /etc/xinetd.d/echo-stream;systemctl restart xinetd;'
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py --node 2 --cmd 'sed -i '\''6s/yes/no/g'\'' /etc/xinetd.d/echo-stream;systemctl restart xinetd;'
Fri Sep  1 20:38:11 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Fri Sep  1 20:38:11 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Sep  1 20:38:12 2023 - INFO  - Start to run test.
+ rdnssd -f
++ pgrep -w nss
+ kill -9 59337 59339
+ rdnssd -H /etc/rdnssd/merge-hook
oe_test_ndisc6_rdnssd.sh: line 26: 59337 Killed                  rdnssd -f
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ ps -aux
++ grep /etc/rdnssd/merge-hook
++ head -n -1
++ awk '{print $2}'
+ kill -9 59341 59342
+ rdnssd -p /var/run/rdnssd.pid
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ ps -aux
++ grep /var/run/rdnssd.pid
++ head -n -1
++ awk '{print $2}'
+ kill -9 59349 59350
+ rdnssd -r /etc/resolv.conf
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ ps -aux
++ grep /etc/resolv.conf
++ head -n -1
++ awk '{print $2}'
+ kill -9 59357 59358
+ rdnssd -u nobody
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ ps -aux
++ grep 'rdnssd -u nobody'
++ head -n -1
++ awk '{print $2}'
+ kill -9 59365 59366
++ rpm -qa ndisc6
++ awk -F - '{print $2}'
+ ndisc6_version=1.0.4
+ rdnssd -V
+ grep 1.0.4
rdnssd: IPv6 Recursive DNS Server discovery Daemon 1.0.4 ($Rev$)
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ rdnssd -h
+ grep rdnssd
Usage: rdnssd [OPTIONS]
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Sep  1 20:38:14 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Fri Sep  1 20:38:14 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Sep  1 20:38:15 2023 - INFO  - Start to restore the test environment.
+ clear_env
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpvq_3t61e ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpvq_3t61e
+ '[' 0 -ne 0 ']'
+ hostname openeuler-riscv64
+ cp -rf /etc/resolv.conf-bak /etc/resolv.conf
+ rm -rf file runtime /etc/resolv.conf-bak
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Sep  1 20:38:26 2023 - INFO  - End to restore the test environment.
